name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: 0816test
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org3a1db36e.crm12.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://cnxv-yuawanos2japanese.crm12.dynamics.com/
      CLIENT_ID: 969ebfe8-02e3-4110-9f4a-f7253cc206f5
      TENANT_ID: f45d97e7-6d68-497b-8ff3-dc640d3317a1   
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
